// Practical-use tooltips for every spell selectable during character creation
// (all cantrips + 1st-level spells across the spellcasting classes). The spell's
// raw mechanical effect already lives in spellData.ts (SpellEntry.desc); these
// lines tell a new player WHEN and WHY to use the spell — the tactical/practical
// angle — so the creation screen teaches play, not just rules text.
//
// Keyed by exact spell name. SpellCard falls back gracefully when a name is absent.

export const SPELL_PRACTICAL: Record<string, string> = {
  // ── Cantrips ──────────────────────────────────────────────────────────────
  "Acid Splash": "Hits two adjacent enemies at once — great for clearing clustered weak foes like goblins or rats.",
  "Blade Ward": "Spend your action to halve incoming weapon damage for a round — a defensive fallback when you're swarmed and out of better options.",
  "Chill Touch": "Stops a target from regaining HP — invaluable against trolls, vampires, and anything that heals or regenerates.",
  "Dancing Lights": "Four movable lights for hands-free illumination or a decoy — light a corridor or lure a guard's attention.",
  "Druidcraft": "Tiny nature magic: predict weather, bloom a flower, light or snuff a small flame — handy utility and roleplay flavor.",
  "Eldritch Blast": "The Warlock's signature attack — long-range force damage that grows as you level. Reliable and rarely resisted; your bread-and-butter.",
  "Fire Bolt": "Your default ranged attack as a Wizard or Sorcerer — also ignites unattended flammables like doors, ropes, or spilled oil.",
  "Friends": "Advantage on Charisma checks against one non-hostile creature — smooth a negotiation, but they realize they were charmed afterward, so use it carefully.",
  "Guidance": "Add 1d4 to one ally's ability check — cast it before lockpicking, persuasion, or any risky skill check to tip the odds.",
  "Light": "Make an object glow like a torch, freeing your hands — touch a pebble and toss it ahead to scout dark rooms.",
  "Mage Hand": "A spectral hand to pull levers, fetch keys, or retrieve items from 30ft — disarm traps and grab loot without risk.",
  "Mending": "Repair a broken tool, torn rope, or cracked vial — quietly fix gear between fights or restore a damaged clue.",
  "Message": "Whisper privately to someone you can see — coordinate a plan silently or talk through a wall.",
  "Minor Illusion": "Conjure a sound or image to distract or mislead — fake a noise to draw a guard, or hide a doorway behind an illusory wall.",
  "Poison Spray": "A burst of toxic gas for strong close-range damage — works on most living things, but not constructs or undead.",
  "Prestidigitation": "All-purpose minor magic: clean, chill, flavor, light a candle — endlessly useful for puzzles, roleplay, and creative problem-solving.",
  "Produce Flame": "A flame for light that doubles as a ranged attack — light the area now, hurl it at an enemy next turn.",
  "Ray of Frost": "Cold damage that also slows the target by 10ft — great for kiting melee enemies and keeping your distance.",
  "Resistance": "Add 1d4 to one ally's saving throw — cast it preemptively when you expect a trap, poison, or breath weapon.",
  "Sacred Flame": "Radiant damage that ignores cover — punishes enemies hiding behind barriers, and radiant bites undead and fiends extra hard.",
  "Shillelagh": "Turns your club or staff into a magic weapon that uses your spell stat to attack — lets a Druid fight in melee without needing Strength.",
  "Shocking Grasp": "Lightning touch with advantage against metal-armored foes; it also denies the target's reactions — escape a melee attacker with no opportunity attack.",
  "Spare the Dying": "Stabilize a dying ally at range with no roll — an instant save when a teammate is bleeding out at 0 HP.",
  "Thaumaturgy": "Booming voice, flickering flames, minor tremors — amplify your presence to intimidate, impress, or signal across a room.",
  "Thorn Whip": "Deals damage and yanks an enemy 10ft toward you — pull a fleeing foe back or drag an archer into your fighter's reach.",
  "True Strike": "Advantage on your next attack — situational; usually just attacking is better, but useful before one high-stakes strike.",
  "Vicious Mockery": "Psychic damage plus disadvantage on the target's next attack — debuff a dangerous attacker while you chip its health.",

  // ── 1st-level spells ──────────────────────────────────────────────────────
  "Absorb Elements": "Reaction when hit by elemental damage: halve it and add bonus damage to your next hit — clutch against dragons and casters.",
  "Alarm": "Ward an area to alert you if something enters — set it before a long rest so no one is ambushed in their sleep.",
  "Animal Friendship": "Convince a beast you're no threat — bypass guard animals or calm a wild creature without a fight (no effect on smart monsters).",
  "Armor of Agathys": "Temp HP plus cold damage to anyone who hits you in melee — bait enemies into attacking and punish them for it.",
  "Arms of Hadar": "Damages everyone around you and denies their reactions — great when surrounded, and it blocks opportunity attacks as you escape.",
  "Bane": "Saddles up to three enemies with -1d4 to attacks and saves — weakens a tough group and boosts your party's save-based spells.",
  "Bless": "Gives three allies +1d4 to attacks and saves — one of the best level-1 buffs; cast it at the start of any serious fight.",
  "Burning Hands": "Cone of fire hitting everything in front of you — ideal for clustered enemies and igniting flammable terrain.",
  "Charm Person": "Make a humanoid see you as a friend — defuse a standoff or get information, but they know they were charmed when it ends.",
  "Chromatic Orb": "You pick the damage type — hurl a high-damage orb of whatever element your enemy is weakest to.",
  "Color Spray": "Blinds a cluster of enemies based on their HP — instantly shut down several weak foes so your party can act freely.",
  "Command": "Force a one-word order — 'Flee', 'Drop', 'Grovel', 'Halt' — to control a key enemy at a crucial moment.",
  "Compelled Duel": "Locks an enemy into fighting you — peel a dangerous attacker off your squishy allies.",
  "Comprehend Languages": "Read or understand any language for an hour — decode inscriptions, contracts, or eavesdrop on enemies.",
  "Create or Destroy Water": "Make or destroy water — fill waterskins, douse flames, or clear a flooded path; pairs with cold spells to make ice.",
  "Cure Wounds": "Solid touch healing — top an ally up between fights or pull someone off the brink in melee.",
  "Detect Evil and Good": "Sense nearby fiends, undead, and celestials — spot a disguised devil or consecrated/cursed ground.",
  "Detect Magic": "Reveal magic auras and their schools nearby — find hidden enchantments, traps, and which loot is worth identifying.",
  "Detect Poison and Disease": "Sense poisons, diseases, and venomous creatures around you — vet a suspicious meal or scout for hidden hazards.",
  "Disguise Self": "Change your look and clothing — slip past guards or impersonate someone (it's an illusion, so a touch reveals it).",
  "Dissonant Whispers": "Psychic damage that forces the target to flee using its reaction — provoke opportunity attacks from your allies as it runs.",
  "Divine Favor": "Adds radiant damage to every weapon hit for a minute — a smite-lite buff that makes your whole turn hit harder.",
  "Ensnaring Strike": "Your next hit roots the enemy in magical thorns, restraining them — lock down a fleeing or dangerous target.",
  "Entangle": "Grasping weeds restrain enemies in a 20ft square — create sticky terrain to slow a charge or trap a group.",
  "Expeditious Retreat": "Dash as a bonus action every turn — reposition fast, escape danger, or run down a fleeing enemy.",
  "Faerie Fire": "Outlines enemies so every attack against them has advantage — devastating versus invisible foes and a force-multiplier for the party.",
  "False Life": "Free temporary HP — cast before a fight for a cushion; especially good on squishy casters.",
  "Feather Fall": "Reaction to save up to five falling creatures — negate fall damage from a pit, cliff, or collapsing floor.",
  "Find Familiar": "Summons a loyal spirit to scout, deliver touch spells, and grant advantage by Helping — one of the most versatile utility spells.",
  "Fog Cloud": "Fills an area with heavy obscurement — break enemy line of sight, cover a retreat, or blind ranged attackers.",
  "Goodberry": "Ten berries that each heal 1 HP and feed someone for a day — emergency healing and an answer to starvation on long journeys.",
  "Grease": "Makes a 10ft square slippery — knock enemies prone, block a doorway, or slide foes off a ledge; it's flammable, too.",
  "Guiding Bolt": "Radiant damage that gives the next attacker advantage on the target — combo it right before an ally's big hit.",
  "Hail of Thorns": "Your next ranged hit also sprays thorns at nearby enemies — turn a single arrow into area damage against a cluster.",
  "Healing Word": "Bonus-action ranged healing — revive a downed ally from across the room while still attacking or moving the same turn.",
  "Hellish Rebuke": "Reaction to engulf whoever just hurt you in flames — punish a big hit with guaranteed fire damage.",
  "Heroism": "Makes an ally immune to fear and feeds them temp HP each round — perfect for the frontline against terrifying foes.",
  "Hex": "Curse a target for bonus damage on your hits plus disadvantage on one ability — stack it on your main attack for a long fight.",
  "Hunter's Mark": "Marks a target for bonus damage on every hit and advantage to track it — the Ranger's go-to single-target damage boost.",
  "Ice Knife": "Throw an icy shard that explodes for cold damage on nearby enemies — single-target plus a splash on the group.",
  "Identify": "Learn an item's properties and how to use it — safely vet mysterious loot before attuning to something cursed.",
  "Illusory Script": "Write a message only your chosen readers understand — pass secret notes that look like gibberish to everyone else.",
  "Inflict Wounds": "Big melee necrotic damage on a hit — a hard-hitting touch attack for a cleric who wants to deal punishment.",
  "Jump": "Triples a creature's jump distance — clear chasms, leap to ledges, or bound out of a tight spot.",
  "Longstrider": "+10ft speed for an hour — keep up on a chase, kite enemies, or cross ground faster on a timed mission.",
  "Mage Armor": "Sets an unarmored ally's AC to 13 + Dex for 8 hours — essential durability for Wizards and Sorcerers who can't wear armor.",
  "Magic Missile": "Three darts of force that auto-hit — never misses, so it's perfect for finishing low-HP enemies or breaking a caster's concentration.",
  "Protection from Evil & Good": "Shields an ally so fiends, undead, and aberrations attack with disadvantage and can't charm or frighten them.",
  "Purify Food and Drink": "Cleanse a meal of poison and rot — neutralize a poisoning attempt or make spoiled supplies safe.",
  "Ray of Sickness": "Poison damage that can also poison the target (disadvantage on attacks and checks) — debuff and damage in one shot.",
  "Sanctuary": "Wards an ally so enemies must pass a save to even target them — protect a downed friend or your healer from being focused.",
  "Searing Smite": "Your next hit deals fire and sets the target burning each turn — ongoing damage that also reveals an invisible foe.",
  "Shield": "Reaction for +5 AC until your next turn — turn a hit into a miss, and it completely blocks Magic Missile.",
  "Shield of Faith": "Bonus-action +2 AC on an ally for 10 minutes — harden your frontliner before they wade in.",
  "Silent Image": "A movable 15ft illusion you control — fake a wall, a monster, or a bridge to mislead enemies and solve obstacles.",
  "Sleep": "Drops the weakest enemies unconscious with no save — shut down a pack of low-HP foes early (it fades as enemies grow tougher).",
  "Speak with Animals": "Talk with beasts for ten minutes — question a guard dog, a horse, or birds that witnessed what happened.",
  "Tasha's Hideous Laughter": "Drops one enemy prone and incapacitated with laughter — take a single dangerous foe out of the fight (best on low-Wisdom brutes).",
  "Thunderous Smite": "Your next hit booms for thunder damage and can knock the target prone — stagger a big enemy mid-swing.",
  "Thunderwave": "A wave of force that damages and shoves everything in a 15ft cube back 10ft — clear clustered enemies or push foes off a ledge.",
  "Unseen Servant": "An invisible helper for menial tasks — carry gear, open doors, fetch items, or trip traps from a safe distance.",
  "Witch Bolt": "A sustained arc of lightning you can repeat each turn — steady single-target damage as long as you hold concentration.",
  "Wrathful Smite": "Your next hit deals psychic damage and can frighten the target — rattle a foe so it attacks at disadvantage and may flee.",
};
