import Image from "next/image";
import Link from "next/link";
import { createClient } from "@supabase/supabase-js";
import "./globals.css";

const CLASS_COLORS: Record<string, string> = {
  Fighter: "#ef4444", Wizard: "#8b5cf6", Rogue: "#94a3b8",
  Cleric: "#f59e0b", Paladin: "#f97316", Ranger: "#22c55e",
  Bard: "#ec4899", Warlock: "#7c3aed", Barbarian: "#dc2626",
  Druid: "#16a34a", Monk: "#0ea5e9", Sorcerer: "#a855f7",
};

async function getAdventurers() {
  try {
    const sb = createClient(
      process.env.NEXT_PUBLIC_SUPABASE_URL!,
      process.env.SUPABASE_SERVICE_ROLE_KEY ?? process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
      { auth: { autoRefreshToken: false, persistSession: false } }
    );
    const { data } = await sb
      .from("characters")
      .select("name, race, class, portrait_url")
      .not("portrait_url", "is", null)
      .neq("portrait_url", "")
      .limit(100);
    if (!data?.length) return [];
    // Fisher-Yates shuffle then take up to 8
    const arr = [...data];
    for (let i = arr.length - 1; i > 0; i--) {
      const j = Math.floor(Math.random() * (i + 1));
      [arr[i], arr[j]] = [arr[j], arr[i]];
    }
    return arr.slice(0, 8).map(c => ({ name: c.name as string, race: c.race as string, cls: c.class as string, url: c.portrait_url as string }));
  } catch {
    return [];
  }
}

const FEATURES = [
  {
    icon: "🧙‍♂️",
    title: "Expert AI Dungeon Master",
    desc: "Claude AI — Anthropic's most capable model — runs your entire world. It knows every D&D 5e rule, monster stat block, and spell interaction. It improvises narrative, reacts to your choices, and crafts encounters that feel earned, dangerous, and rewarding.",
  },
  {
    icon: "⚔️",
    title: "Full Combat Engine",
    desc: "Initiative order, attack rolls, saving throws, spell slots, conditions, AOE effects — all tracked automatically. The AI DM narrates every critical hit and death save with dramatic flair while the rules engine handles the math.",
  },
  {
    icon: "🌍",
    title: "Real-Time Multiplayer",
    desc: "Start a campaign and share a single invite link. Up to 10 players join the same living world, each controlling their own hero. Every action, dialogue choice, and dice roll syncs live across the entire party.",
  },
  {
    icon: "🎨",
    title: "AI Portrait Generation",
    desc: "Every character you create gets a unique painted portrait generated by DALL-E based on your race, class, and appearance. Your hero looks exactly how you imagined them — before the adventure even begins.",
  },
];

const STEPS = [
  {
    n: "01",
    icon: "⚒️",
    title: "Forge Your Hero",
    desc: "Pick your race, class, background, and stats. The AI generates a one-of-a-kind painted portrait just for your character.",
  },
  {
    n: "02",
    icon: "🗺️",
    title: "Start or Join a Campaign",
    desc: "Create your own campaign or join a friend's with an invite link. Solo or a full party — no setup required.",
  },
  {
    n: "03",
    icon: "📖",
    title: "Let the Legend Begin",
    desc: "The AI Dungeon Master takes over. It builds the world, runs the encounters, and weaves your story — session after session.",
  },
];

export default async function Home() {
  const adventurers = await getAdventurers();
  return (
    <main style={{ minHeight: "100vh", display: "flex", flexDirection: "column" }}>

      {/* ── Navigation ─────────────────────────────────────────────────────── */}
      <nav className="glass-panel" style={{ margin: "20px", padding: "16px 32px", display: "flex", justifyContent: "space-between", alignItems: "center", zIndex: 10 }}>
        <div style={{ fontSize: "1.5rem", fontWeight: "bold", display: "flex", alignItems: "center", gap: "10px" }}>
          <span style={{ color: "var(--primary)" }}>⬡</span>
          <span>Dungeons &amp; Dinner Legends</span>
        </div>
        <Link href="/auth"><button className="btn-secondary">Log In</button></Link>
      </nav>

      {/* ── Hero ───────────────────────────────────────────────────────────── */}
      <section style={{ minHeight: "90vh", display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center", textAlign: "center", padding: "60px 20px 80px", position: "relative" }}>
        <div style={{ position: "absolute", inset: 0, zIndex: -2 }}>
          <Image src="/hero_bg.png" alt="" fill style={{ objectFit: "cover", opacity: 0.13, mixBlendMode: "screen" }} priority />
        </div>
        <div style={{ position: "absolute", top: "5%", left: "8%", width: "500px", height: "500px", background: "var(--primary)", filter: "blur(180px)", opacity: 0.13, zIndex: -1, borderRadius: "50%" }} />
        <div style={{ position: "absolute", bottom: "5%", right: "8%", width: "420px", height: "420px", background: "#f59e0b", filter: "blur(180px)", opacity: 0.07, zIndex: -1, borderRadius: "50%" }} />

        <h1 className="animate-fade-in shimmer-heading" style={{ fontSize: "clamp(2.8rem, 8vw, 5.5rem)", fontWeight: 900, maxWidth: "880px", margin: "28px 0 24px", lineHeight: 1.05 }}>
          Your Next Great<br />Adventure Awaits
        </h1>

        <p className="animate-fade-in delay-200" style={{ fontSize: "clamp(1rem, 2.5vw, 1.2rem)", color: "var(--subtle)", maxWidth: "600px", marginBottom: "52px", lineHeight: 1.8 }}>
          The world&apos;s first fully AI-powered D&amp;D 5e experience. No human DM needed —
          Claude AI runs your world, your enemies, your story. Every player gets a seat at the table.
        </p>

        <div className="animate-fade-in delay-300" style={{ display: "flex", gap: "16px", flexWrap: "wrap", justifyContent: "center" }}>
          <Link href="/auth">
            <button className="btn-primary" style={{ fontSize: "1.1rem", padding: "16px 40px" }}>
              Enter the Tavern
            </button>
          </Link>
          <a href="#how-it-works">
            <button className="btn-secondary" style={{ fontSize: "1rem", padding: "16px 28px" }}>
              How It Works ↓
            </button>
          </a>
        </div>

        {/* Stats strip */}
        <div className="animate-fade-in delay-300" style={{ display: "flex", gap: "48px", marginTop: "72px", flexWrap: "wrap", justifyContent: "center" }}>
          {[
            { value: "5e", label: "D&D Rules" },
            { value: "10", label: "Players / Campaign" },
            { value: "AI", label: "Dungeon Master" },
            { value: "∞", label: "Unique Stories" },
          ].map(({ value, label }) => (
            <div key={label} style={{ textAlign: "center" }}>
              <div style={{ fontSize: "clamp(1.6rem, 4vw, 2.4rem)", fontWeight: 900, color: "white", letterSpacing: "-0.02em" }}>{value}</div>
              <div style={{ fontSize: "0.72rem", color: "var(--muted)", textTransform: "uppercase", letterSpacing: "0.1em", marginTop: "4px" }}>{label}</div>
            </div>
          ))}
        </div>
      </section>

      {/* ── Adventurers Showcase ───────────────────────────────────────────── */}
      {adventurers.length > 0 && <section style={{ padding: "80px 20px", textAlign: "center", borderTop: "1px solid var(--border)", position: "relative", overflow: "hidden" }}>
        <div style={{ position: "absolute", top: "50%", left: "50%", transform: "translate(-50%,-50%)", width: "700px", height: "350px", background: "var(--primary)", filter: "blur(160px)", opacity: 0.055, zIndex: 0 }} />
        <div style={{ position: "relative", zIndex: 1 }}>
          <p style={{ color: "var(--primary)", fontSize: "0.8rem", fontWeight: 700, letterSpacing: "0.1em", textTransform: "uppercase", marginBottom: "12px" }}>Real Players. Real Characters.</p>
          <h2 style={{ fontSize: "clamp(1.6rem, 4vw, 2.5rem)", fontWeight: 800, marginBottom: "14px" }}>Meet the Adventurers</h2>
          <p style={{ color: "var(--subtle)", maxWidth: "500px", margin: "0 auto 52px", lineHeight: 1.75 }}>
            Every character gets a one-of-a-kind AI-painted portrait the moment they&apos;re created.
            These are real heroes forged by real players.
          </p>
          <div style={{ display: "flex", gap: "28px", justifyContent: "center", flexWrap: "wrap", maxWidth: "1100px", margin: "0 auto" }}>
            {adventurers.map(({ name, race, cls, url }, i) => {
              const color = CLASS_COLORS[cls] ?? "var(--primary)";
              return (
                <div key={name} className="animate-float" style={{ display: "flex", flexDirection: "column", alignItems: "center", gap: "10px", animationDelay: `${i * 0.4}s` }}>
                  <div
                    className="portrait-ring"
                    style={{ border: `3px solid ${color}`, boxShadow: `0 0 22px ${color}50, 0 4px 20px rgba(0,0,0,0.55)` }}
                  >
                    {/* eslint-disable-next-line @next/next/no-img-element */}
                    <img src={url} alt={name} style={{ width: "100%", height: "100%", objectFit: "cover" }} loading="lazy" />
                  </div>
                  <div style={{ textAlign: "center" }}>
                    <div style={{ fontSize: "0.82rem", fontWeight: 600, color: "#e2e8f0" }}>{name}</div>
                    <div style={{ fontSize: "0.72rem", color, fontWeight: 600, marginTop: "2px" }}>{race} {cls}</div>
                  </div>
                </div>
              );
            })}
          </div>
        </div>
      </section>}

      {/* ── What Is This ──────────────────────────────────────────────────── */}
      <section style={{ padding: "80px 20px", borderTop: "1px solid var(--border)" }}>
        <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(300px, 1fr))", gap: "64px", alignItems: "center", maxWidth: "1100px", margin: "0 auto" }}>
          <div>
            <p style={{ color: "var(--primary)", fontSize: "0.8rem", fontWeight: 700, letterSpacing: "0.1em", textTransform: "uppercase", marginBottom: "12px" }}>No Human DM Required</p>
            <h2 style={{ fontSize: "clamp(1.8rem, 4vw, 2.8rem)", fontWeight: 900, lineHeight: 1.2, marginBottom: "24px" }}>
              The AI Runs the World.<br />
              <span style={{ color: "var(--primary)" }}>You Just Play.</span>
            </h2>
            <p style={{ color: "var(--subtle)", lineHeight: 1.85, marginBottom: "20px", fontSize: "0.97rem" }}>
              Dungeons and Dinner Legends puts Claude AI — Anthropic&apos;s most powerful model — in the Dungeon Master&apos;s seat.
              It runs enemies, NPCs, encounters, loot drops, and the overarching narrative without any human oversight.
            </p>
            <p style={{ color: "var(--subtle)", lineHeight: 1.85, fontSize: "0.97rem" }}>
              Every person at the table plays a character. No one sits out to manage the game.
              Just show up with your hero and dive into a living world that remembers every choice you make.
            </p>
          </div>
          <div style={{ display: "flex", flexDirection: "column", gap: "14px" }}>
            {[
              "Follows D&D 5e rules faithfully — spells, conditions, and stat blocks all correct",
              "Reacts to your choices in real time, crafting fresh narrative on the fly",
              "Tracks all combat: initiative, HP, spell slots, conditions, and loot",
              "Runs NPCs, merchants, villains, and wandering monsters autonomously",
              "Works solo or with a full party of up to 10 players",
              "Every session continues the story exactly where you left off",
            ].map((text) => (
              <div key={text} style={{ display: "flex", gap: "12px", alignItems: "flex-start" }}>
                <span style={{ color: "var(--primary)", marginTop: "3px", flexShrink: 0, fontSize: "0.85rem" }}>✦</span>
                <span style={{ color: "#cbd5e1", lineHeight: 1.65, fontSize: "0.93rem" }}>{text}</span>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ── Features ───────────────────────────────────────────────────────── */}
      <section style={{ padding: "80px 20px", borderTop: "1px solid var(--border)", textAlign: "center" }}>
        <p style={{ color: "var(--primary)", fontSize: "0.8rem", fontWeight: 700, letterSpacing: "0.1em", textTransform: "uppercase", marginBottom: "12px" }}>Everything You Need</p>
        <h2 style={{ fontSize: "clamp(1.6rem, 4vw, 2.5rem)", fontWeight: 800, marginBottom: "14px" }}>Built for the Full Experience</h2>
        <p style={{ color: "var(--subtle)", maxWidth: "500px", margin: "0 auto 52px", lineHeight: 1.75 }}>
          Every system of D&amp;D 5e, faithfully implemented — so you can focus on the adventure.
        </p>
        <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(260px, 1fr))", gap: "20px", maxWidth: "1100px", margin: "0 auto" }}>
          {FEATURES.map(({ icon, title, desc }, i) => (
            <div key={title} className="glass-panel feature-card-lg animate-float" style={{ animationDelay: `${i * 0.75}s` }}>
              <div style={{ fontSize: "2.2rem" }}>{icon}</div>
              <h3 style={{ fontSize: "1.05rem", fontWeight: 700, color: "white" }}>{title}</h3>
              <p style={{ color: "var(--subtle)", fontSize: "0.88rem", lineHeight: 1.75 }}>{desc}</p>
            </div>
          ))}
        </div>
      </section>

      {/* ── How It Works ───────────────────────────────────────────────────── */}
      <section id="how-it-works" style={{ padding: "80px 20px", borderTop: "1px solid var(--border)", textAlign: "center" }}>
        <p style={{ color: "var(--primary)", fontSize: "0.8rem", fontWeight: 700, letterSpacing: "0.1em", textTransform: "uppercase", marginBottom: "12px" }}>Simple as Rolling a D20</p>
        <h2 style={{ fontSize: "clamp(1.6rem, 4vw, 2.5rem)", fontWeight: 800, marginBottom: "52px" }}>How to Play</h2>
        <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(260px, 1fr))", gap: "24px", maxWidth: "900px", margin: "0 auto" }}>
          {STEPS.map(({ n, icon, title, desc }) => (
            <div key={n} className="glass-panel step-card">
              <div style={{ position: "absolute", top: "-8px", right: "18px", fontSize: "4.5rem", fontWeight: 900, color: "rgba(139,92,246,0.07)", lineHeight: 1, userSelect: "none", pointerEvents: "none" }}>{n}</div>
              <div style={{ fontSize: "2rem", marginBottom: "14px" }}>{icon}</div>
              <h3 style={{ fontSize: "1.05rem", fontWeight: 700, marginBottom: "10px", color: "white" }}>{title}</h3>
              <p style={{ color: "var(--subtle)", fontSize: "0.88rem", lineHeight: 1.75 }}>{desc}</p>
            </div>
          ))}
        </div>
      </section>

      {/* ── Final CTA ──────────────────────────────────────────────────────── */}
      <section style={{ padding: "100px 20px", textAlign: "center", borderTop: "1px solid var(--border)", position: "relative" }}>
        <div style={{ position: "absolute", top: "50%", left: "50%", transform: "translate(-50%,-50%)", width: "600px", height: "300px", background: "var(--primary)", filter: "blur(160px)", opacity: 0.09, zIndex: 0 }} />
        <div style={{ position: "relative", zIndex: 1 }}>
          <h2 style={{ fontSize: "clamp(2rem, 5vw, 3.5rem)", fontWeight: 900, marginBottom: "20px", background: "linear-gradient(160deg, #fff 30%, #c4b5fd)", WebkitBackgroundClip: "text", WebkitTextFillColor: "transparent" }}>
            Ready to Begin Your Legend?
          </h2>
          <p style={{ color: "var(--subtle)", fontSize: "1.05rem", maxWidth: "460px", margin: "0 auto 44px", lineHeight: 1.8 }}>
            Your adventure is one click away. Forge your hero and step into a world that never ends.
          </p>
          <Link href="/auth">
            <button className="btn-primary" style={{ fontSize: "1.15rem", padding: "18px 52px" }}>
              Enter the Tavern
            </button>
          </Link>
        </div>
      </section>

      {/* ── Publisher Badge ─────────────────────────────────────────────────── */}
      <div style={{ position: "fixed", bottom: "20px", right: "20px", zIndex: 50, background: "white", borderRadius: "12px", padding: "8px", boxShadow: "0 4px 20px rgba(0,0,0,0.4)", display: "flex", alignItems: "center", justifyContent: "center" }}>
        {/* eslint-disable-next-line @next/next/no-img-element */}
        <img src="/DrinkPlayLogo.jpg" alt="Drink and Play Publishing" style={{ width: "90px", height: "90px", objectFit: "contain", display: "block", borderRadius: "6px" }} />
      </div>
    </main>
  );
}
