import Image from "next/image";
import Link from "next/link";
import { createClient } from "@supabase/supabase-js";
import "./globals.css";
import LandingNav from "../components/LandingNav";

const CLASS_COLORS: Record<string, string> = {
  Fighter: "#ef4444", Wizard: "#8b5cf6", Rogue: "#94a3b8",
  Cleric: "#f59e0b", Paladin: "#f97316", Ranger: "#22c55e",
  Bard: "#ec4899", Warlock: "#7c3aed", Barbarian: "#dc2626",
  Druid: "#16a34a", Monk: "#0ea5e9", Sorcerer: "#a855f7",
};

async function getAdventurers() {
  try {
    const sb = createClient(
      process.env.NEXT_PUBLIC_SUPABASE_URL!,
      process.env.SUPABASE_SERVICE_ROLE_KEY ?? process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
      { auth: { autoRefreshToken: false, persistSession: false } }
    );
    const { data } = await sb
      .from("characters")
      .select("name, race, class, portrait_url")
      .not("portrait_url", "is", null)
      .neq("portrait_url", "")
      .limit(100);
    if (!data?.length) return [];
    const arr = [...data];
    for (let i = arr.length - 1; i > 0; i--) {
      const j = Math.floor(Math.random() * (i + 1));
      [arr[i], arr[j]] = [arr[j], arr[i]];
    }
    return arr.slice(0, 8).map(c => ({ name: c.name as string, race: c.race as string, cls: c.class as string, url: c.portrait_url as string }));
  } catch {
    return [];
  }
}

const FEATURES = [
  {
    icon: "🧙‍♂️",
    title: "Expert AI Dungeon Master",
    desc: "Claude AI — Anthropic's most capable model — runs your entire world. Every rule, every monster, every plot twist. Fully autonomous.",
  },
  {
    icon: "⚔️",
    title: "Full Combat Engine",
    desc: "Initiative, attack rolls, saving throws, spell slots, conditions — all tracked automatically while the AI narrates every critical hit.",
  },
  {
    icon: "🌍",
    title: "Real-Time Multiplayer",
    desc: "Share one link. Up to 10 players join the same living world. Every roll and choice syncs live across the entire party.",
  },
  {
    icon: "🎨",
    title: "AI Portrait Generation",
    desc: "Every character gets a unique painted portrait generated by DALL-E from your race, class, and appearance. Your hero, visualized.",
  },
];

const STEPS = [
  {
    n: "01",
    icon: "⚒️",
    title: "Forge Your Hero",
    desc: "Pick race, class, background, and stats. The AI paints a one-of-a-kind portrait just for your character.",
  },
  {
    n: "02",
    icon: "🗺️",
    title: "Start or Join a Campaign",
    desc: "Create your own adventure or join a friend with an invite link. Solo or full party — no setup required.",
  },
  {
    n: "03",
    icon: "📖",
    title: "Let the Legend Begin",
    desc: "The AI Dungeon Master takes over: builds the world, runs the encounters, and weaves your story — session after session.",
  },
];

export default async function Home() {
  const adventurers = await getAdventurers();
  return (
    <main style={{ minHeight: "100vh", display: "flex", flexDirection: "column" }}>

      <LandingNav />

      {/* ── Hero ─────────────────────────────────────────────────────────────── */}
      <section style={{
        minHeight: "100vh",
        display: "flex",
        flexDirection: "column",
        alignItems: "center",
        justifyContent: "center",
        textAlign: "center",
        padding: "100px 24px 80px",
        position: "relative",
        overflow: "hidden",
      }}>
        {/* Deep background glow */}
        <div style={{ position: "absolute", inset: 0, zIndex: 0, background: "radial-gradient(ellipse 90% 55% at 50% 48%, rgba(30,27,75,0.85) 0%, transparent 70%)" }} />
        <div style={{ position: "absolute", top: "20%", left: "50%", transform: "translateX(-50%)", width: "800px", height: "400px", background: "var(--primary)", filter: "blur(220px)", opacity: 0.1, zIndex: 0 }} />

        {/* Dragon — left, contained to its half with inner fade */}
        <div className="hero-img-panel hero-img-left animate-float" style={{ animationDelay: "0.3s" }}>
          <Image src="/Dragon_Ramen.png" alt="" fill style={{ objectFit: "contain", objectPosition: "right center" }} priority />
          <div className="hero-fade-right" />
        </div>

        {/* Party — right, contained to its half with inner fade */}
        <div className="hero-img-panel hero-img-right animate-float" style={{ animationDelay: "1.1s" }}>
          <Image src="/GangGang.png" alt="" fill style={{ objectFit: "contain", objectPosition: "left center" }} priority />
          <div className="hero-fade-left" />
        </div>

        {/* Center content — above images */}
        <div style={{ position: "relative", zIndex: 2, display: "flex", flexDirection: "column", alignItems: "center", maxWidth: "680px" }}>
          <div className="animate-fade-in" style={{
            display: "inline-block",
            background: "linear-gradient(135deg, rgba(139,92,246,0.18), rgba(245,158,11,0.12))",
            border: "1px solid rgba(139,92,246,0.3)",
            borderRadius: "100px",
            padding: "6px 18px",
            fontSize: "0.72rem",
            fontWeight: 700,
            letterSpacing: "0.12em",
            textTransform: "uppercase",
            color: "#c4b5fd",
            marginBottom: "28px",
          }}>
            AI-Powered Dungeon Crawler Experience
          </div>

          <h1 className="animate-fade-in delay-100 shimmer-heading" style={{
            fontSize: "clamp(3rem, 7vw, 5.8rem)",
            fontWeight: 900,
            lineHeight: 1.04,
            letterSpacing: "-0.02em",
            marginBottom: "28px",
          }}>
            Your Next Great<br />Adventure Awaits
          </h1>

          <p className="animate-fade-in delay-200" style={{
            fontSize: "clamp(1rem, 2vw, 1.15rem)",
            color: "var(--subtle)",
            maxWidth: "520px",
            marginBottom: "44px",
            lineHeight: 1.85,
          }}>
            No human DM needed. Claude AI runs your world, your enemies, your story.
            Every player gets a seat at the table.
          </p>

          <div className="animate-fade-in delay-300" style={{ display: "flex", gap: "14px", flexWrap: "wrap", justifyContent: "center" }}>
            <Link href="/auth">
              <button className="btn-primary" style={{ fontSize: "1.05rem", padding: "16px 44px", borderRadius: "10px" }}>
                Enter the Tavern
              </button>
            </Link>
            <a href="#how-it-works">
              <button className="btn-secondary" style={{ fontSize: "0.97rem", padding: "16px 28px", borderRadius: "10px" }}>
                How It Works ↓
              </button>
            </a>
          </div>

          {/* Stats strip */}
          <div className="animate-fade-in delay-300" style={{
            display: "flex",
            gap: "0",
            marginTop: "64px",
            background: "rgba(255,255,255,0.03)",
            border: "1px solid rgba(255,255,255,0.08)",
            borderRadius: "16px",
            overflow: "hidden",
          }}>
            {[
              { value: "5e", label: "Dungeons and Dinners" },
              { value: "10", label: "Players Max" },
              { value: "AI", label: "Dungeon Master" },
              { value: "∞", label: "Unique Stories" },
            ].map(({ value, label }, i) => (
              <div key={label} style={{
                textAlign: "center",
                padding: "20px 32px",
                borderRight: i < 3 ? "1px solid rgba(255,255,255,0.07)" : "none",
              }}>
                <div style={{ fontSize: "clamp(1.5rem, 3.5vw, 2.2rem)", fontWeight: 900, color: "white", letterSpacing: "-0.02em" }}>{value}</div>
                <div style={{ fontSize: "0.68rem", color: "var(--muted)", textTransform: "uppercase", letterSpacing: "0.1em", marginTop: "4px" }}>{label}</div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ── Adventurers Showcase ──────────────────────────────────────────────── */}
      {adventurers.length > 0 && (
        <section style={{ padding: "100px 24px", textAlign: "center", borderTop: "1px solid var(--border)", position: "relative", overflow: "hidden" }}>
          <div style={{ position: "absolute", top: "50%", left: "50%", transform: "translate(-50%,-50%)", width: "800px", height: "400px", background: "var(--primary)", filter: "blur(180px)", opacity: 0.06, zIndex: 0 }} />
          <div style={{ position: "relative", zIndex: 1 }}>
            <p style={{ color: "var(--primary)", fontSize: "0.78rem", fontWeight: 700, letterSpacing: "0.12em", textTransform: "uppercase", marginBottom: "14px" }}>Real Players. Real Characters.</p>
            <h2 style={{ fontSize: "clamp(1.8rem, 4vw, 2.8rem)", fontWeight: 800, marginBottom: "16px" }}>Meet the Adventurers</h2>
            <p style={{ color: "var(--subtle)", maxWidth: "480px", margin: "0 auto 60px", lineHeight: 1.8, fontSize: "0.95rem" }}>
              Every character gets a one-of-a-kind AI-painted portrait the moment they&apos;re created.
            </p>

            <div style={{
              display: "flex",
              gap: "24px",
              justifyContent: "center",
              flexWrap: "wrap",
              maxWidth: "1200px",
              margin: "0 auto",
            }}>
              {adventurers.map(({ name, race, cls, url }, i) => {
                const color = CLASS_COLORS[cls] ?? "var(--primary)";
                return (
                  <div key={name} className="portrait-card" style={{ animationDelay: `${i * 0.3}s` }}>
                    <div style={{
                      position: "relative",
                      width: "100%",
                      aspectRatio: "3/4",
                      overflow: "hidden",
                      borderRadius: "12px 12px 0 0",
                    }}>
                      {/* eslint-disable-next-line @next/next/no-img-element */}
                      <img src={url} alt={name} style={{ width: "100%", height: "100%", objectFit: "cover", display: "block" }} loading="lazy" />
                      <div style={{
                        position: "absolute",
                        inset: 0,
                        background: `linear-gradient(to top, ${color}22 0%, transparent 50%)`,
                        pointerEvents: "none",
                      }} />
                    </div>
                    <div style={{
                      padding: "14px 16px",
                      background: `linear-gradient(135deg, rgba(22,30,50,0.95), rgba(15,20,40,0.98))`,
                      borderTop: `2px solid ${color}55`,
                      borderRadius: "0 0 12px 12px",
                    }}>
                      <div style={{ fontSize: "0.88rem", fontWeight: 700, color: "#f1f5f9", marginBottom: "3px" }}>{name}</div>
                      <div style={{ fontSize: "0.72rem", color, fontWeight: 600, letterSpacing: "0.04em" }}>{race} · {cls}</div>
                    </div>
                  </div>
                );
              })}
            </div>
          </div>
        </section>
      )}

      {/* ── What Is This ─────────────────────────────────────────────────────── */}
      <section style={{ padding: "100px 24px", borderTop: "1px solid var(--border)" }}>
        <div style={{
          display: "grid",
          gridTemplateColumns: "repeat(auto-fit, minmax(320px, 1fr))",
          gap: "72px",
          alignItems: "center",
          maxWidth: "1100px",
          margin: "0 auto",
        }}>
          <div>
            <p style={{ color: "var(--primary)", fontSize: "0.78rem", fontWeight: 700, letterSpacing: "0.12em", textTransform: "uppercase", marginBottom: "14px" }}>No Human DM Required</p>
            <h2 style={{ fontSize: "clamp(1.9rem, 4vw, 2.9rem)", fontWeight: 900, lineHeight: 1.18, marginBottom: "28px" }}>
              The AI Runs the World.<br />
              <span style={{ color: "var(--primary)" }}>You Just Play.</span>
            </h2>
            <p style={{ color: "var(--subtle)", lineHeight: 1.9, marginBottom: "22px", fontSize: "0.96rem" }}>
              Dungeons &amp; Dinner Legends puts Claude AI in the Dungeon Master&apos;s seat.
              It runs enemies, NPCs, encounters, loot, and the overarching narrative — completely autonomously.
            </p>
            <p style={{ color: "var(--subtle)", lineHeight: 1.9, fontSize: "0.96rem" }}>
              Every person at the table plays a character. No one sits out to manage the game.
              Just show up with your hero and dive in.
            </p>
          </div>
          <div style={{ display: "flex", flexDirection: "column", gap: "16px" }}>
            {[
              "Follows Dungeons and Dinners rules faithfully — spells, conditions, and stat blocks all correct",
              "Reacts to your choices in real time, crafting fresh narrative on the fly",
              "Tracks all combat: initiative, HP, spell slots, conditions, and loot",
              "Runs NPCs, merchants, villains, and wandering monsters autonomously",
              "Works solo or with a full party of up to 10 players",
              "Every session continues the story exactly where you left off",
            ].map((text) => (
              <div key={text} style={{ display: "flex", gap: "14px", alignItems: "flex-start" }}>
                <span style={{ color: "var(--primary)", marginTop: "3px", flexShrink: 0, fontSize: "0.85rem" }}>✦</span>
                <span style={{ color: "#cbd5e1", lineHeight: 1.7, fontSize: "0.94rem" }}>{text}</span>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ── Features ─────────────────────────────────────────────────────────── */}
      <section style={{ padding: "100px 24px", borderTop: "1px solid var(--border)", textAlign: "center" }}>
        <p style={{ color: "var(--primary)", fontSize: "0.78rem", fontWeight: 700, letterSpacing: "0.12em", textTransform: "uppercase", marginBottom: "14px" }}>Everything You Need</p>
        <h2 style={{ fontSize: "clamp(1.8rem, 4vw, 2.7rem)", fontWeight: 800, marginBottom: "16px" }}>Built for the Full Experience</h2>
        <p style={{ color: "var(--subtle)", maxWidth: "480px", margin: "0 auto 60px", lineHeight: 1.8, fontSize: "0.95rem" }}>
          Every system of Dungeons and Dinners, faithfully implemented — so you can focus on the adventure.
        </p>
        <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(260px, 1fr))", gap: "20px", maxWidth: "1100px", margin: "0 auto" }}>
          {FEATURES.map(({ icon, title, desc }, i) => (
            <div key={title} className="glass-panel feature-card-lg animate-float" style={{ animationDelay: `${i * 0.7}s` }}>
              <div style={{ fontSize: "2.4rem" }}>{icon}</div>
              <h3 style={{ fontSize: "1.06rem", fontWeight: 700, color: "white" }}>{title}</h3>
              <p style={{ color: "var(--subtle)", fontSize: "0.88rem", lineHeight: 1.8 }}>{desc}</p>
            </div>
          ))}
        </div>
      </section>

      {/* ── How It Works ─────────────────────────────────────────────────────── */}
      <section id="how-it-works" style={{ padding: "100px 24px", borderTop: "1px solid var(--border)", textAlign: "center" }}>
        <p style={{ color: "var(--primary)", fontSize: "0.78rem", fontWeight: 700, letterSpacing: "0.12em", textTransform: "uppercase", marginBottom: "14px" }}>Simple as Rolling a D20</p>
        <h2 style={{ fontSize: "clamp(1.8rem, 4vw, 2.7rem)", fontWeight: 800, marginBottom: "60px" }}>How to Play</h2>
        <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(260px, 1fr))", gap: "24px", maxWidth: "900px", margin: "0 auto" }}>
          {STEPS.map(({ n, icon, title, desc }) => (
            <div key={n} className="glass-panel step-card">
              <div style={{ position: "absolute", top: "-4px", right: "18px", fontSize: "5rem", fontWeight: 900, color: "rgba(139,92,246,0.07)", lineHeight: 1, userSelect: "none", pointerEvents: "none" }}>{n}</div>
              <div style={{ fontSize: "2.2rem", marginBottom: "16px" }}>{icon}</div>
              <h3 style={{ fontSize: "1.06rem", fontWeight: 700, marginBottom: "12px", color: "white" }}>{title}</h3>
              <p style={{ color: "var(--subtle)", fontSize: "0.88rem", lineHeight: 1.8 }}>{desc}</p>
            </div>
          ))}
        </div>
      </section>

      {/* ── Final CTA ────────────────────────────────────────────────────────── */}
      <section style={{ padding: "120px 24px", textAlign: "center", borderTop: "1px solid var(--border)", position: "relative" }}>
        <div style={{ position: "absolute", top: "50%", left: "50%", transform: "translate(-50%,-50%)", width: "700px", height: "350px", background: "var(--primary)", filter: "blur(180px)", opacity: 0.1, zIndex: 0 }} />
        <div style={{ position: "relative", zIndex: 1 }}>
          <h2 style={{
            fontSize: "clamp(2.2rem, 5vw, 3.8rem)",
            fontWeight: 900,
            marginBottom: "24px",
            background: "linear-gradient(155deg, #ffffff 25%, #c4b5fd 60%, #f59e0b 100%)",
            WebkitBackgroundClip: "text",
            WebkitTextFillColor: "transparent",
            lineHeight: 1.1,
          }}>
            Ready to Begin<br />Your Legend?
          </h2>
          <p style={{ color: "var(--subtle)", fontSize: "1.05rem", maxWidth: "420px", margin: "0 auto 48px", lineHeight: 1.85 }}>
            Your adventure is one click away. Forge your hero and step into a world that never ends.
          </p>
          <Link href="/auth">
            <button className="btn-primary" style={{ fontSize: "1.15rem", padding: "20px 60px", borderRadius: "12px" }}>
              Enter the Tavern
            </button>
          </Link>
        </div>
      </section>

      {/* ── Publisher Badge ───────────────────────────────────────────────────── */}
      <div style={{
        position: "fixed", bottom: "20px", right: "20px", zIndex: 50,
        background: "white", borderRadius: "14px", padding: "8px",
        boxShadow: "0 0 0 1px rgba(139,92,246,0.35), 0 0 24px rgba(139,92,246,0.45), 0 0 52px rgba(139,92,246,0.2), 0 8px 32px rgba(0,0,0,0.55)",
      }}>
        {/* eslint-disable-next-line @next/next/no-img-element */}
        <img src="/DrinkPlayLogo.jpg" alt="Drink and Play Publishing" style={{ width: "120px", height: "120px", objectFit: "cover", display: "block", borderRadius: "8px" }} />
      </div>
    </main>
  );
}
